https://notebook.zohopublic.in/public/notes/bietvc07e6ecf28d7409286145c16e623f9ed
https://notebook.zohopublic.in/public/notes/74tdo33c5b7060d544b1c986e519dd3ba4d1b
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern-1_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern_-_2nd_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/LLDElevatorDesign?ref_type=heads
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/LLDCarRentalSystem?ref_type=heads
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignPatterns/LLDChainResponsibilityDesignPattern
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/LLDSnakeLadder
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/DesignDataStructures/MyHashMap.java
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignBookMyShow
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignVendingMachine
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignATM
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignPatterns/CompositeDesignPattern
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignPatterns/AdapterDesignPattern
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignSplitwise
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignPatterns/BuilderDesignPattern
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern-1_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern_-_2nd_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/LLDCricbuzz
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern-1_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/All_Creational_Pattern_-_2nd_Screenshot.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignOrderManagementSystem
https://gitlab.com/shrayansh8/interviewcodingpractise/-/blob/main/src/LowLevelDesign/DesignOrderManagementSystem/UML.png
https://gitlab.com/shrayansh8/interviewcodingpractise/-/tree/main/src/LowLevelDesign/DesignPatterns/FlyWeightPattern
https://notebook.zohopublic.in/public/notes/u3i1s7022b343ebda42819272312415abb520
https://notebook.zohopublic.in/public/notes/74tdoc98e8bf3884241e4ba22312a925a6db2
https://notebook.zohopublic.in/public/notes/74tdo7a52b1936e404254ab8825d8c12a0487
https://notebook.zohopublic.in/public/notes/74tdo731a02767be840f4a81c55515cc3c8f0
https://notebook.zohopublic.in/public/notes/74tdo42f55986906f4882b69fb64c628ae209
https://notebook.zohopublic.in/public/notes/74tdo9c0a25404d6d49a5b679cfe90ed19d48
https://notebook.zohopublic.in/public/notes/bietv6993f5a023ec4e9f89436149ac3ed2f7
https://notebook.zohopublic.in/public/notes/dcr5za494c035adb441818e2bc20485b4de58
